### ISSUE TITLE
G-value

### ISSUE THREAD

**Issue by FlowerPower93** [utaresearch/gMicroMC#6]
Hi, I have read the two articles linked to this project and tried to run the code myself. I have not clear if the G-values of the different free radicals (plotted as a function of time in the articles) are obtained directly somewhere in the outputs or it is calculated later from the outputs.
In the first scenario, in which output file is that saved?

Thanks

**Comment by laiyf94** [comment]
Hi, the G values were acquired later from the output. Notice d_ptype pointer has stored all the information of radicals types. You can calculated the number of each radicals and output them. Check how the information was outputed in the function runMicroMC.cu of chemical stage (line 437 to 464) and make your own style to store the information. 
On the other hand, I have revised the function so that the number of radicals after each step was written into files in function runMicroMC.cu of chemical stage, which is commented now. But to calculate G values, you must need to know the deposited energy as well, which means you need to record the energy in the same region where you record radicals. It is done in physics stage. Check line 1200 and total_e is the value you should output. Then G values can be acquired by dividing the number of radicals by the deposited energy.
As you may notice, there is inconvenience now. The scoring actually need information-sharing bewteen different stages. We are working to have a final version, which integrate all the stages and have files and function names organized. And more comments of course. The newer version should be released in another one or two weeks. Please wait for the good news if you feel difficult to implement your own function in this version.

**Comment by FlowerPower93** [comment]
I was wondering if you might share how do you read the binary files and combine their information to calculate the G-value.

I am trying to use this code along with Geant4, what lower energy cut is used for the produced electrons in gMicro?

Thank you
